# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'  
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Setup NuGet'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'TZ.vNext.Web'

- task: CmdLine@2
  displayName: 'replacer'
  inputs:
    script: '"CIScript/Replacer.exe" "TZ.vNext.Web/node_modules/vue-router/types/router.d.ts" "import Vue = require("vue")" "import Vue from "vue""'


- task: CmdLine@2
  inputs:
    script: 'dir TZ.vNext.Web'

- task: CmdLine@2
  inputs:
    script: 'type "TZ.vNext.Web/node_modules/vue-router/types/router.d.ts"'

# - task: NuGetCommand@2
#   displayName: 'Authenticate with Azure DevOps NuGet'
#   inputs:
#     command: custom
#     arguments: sources add -name 'telerik.com' -source 'https://nuget.telerik.com/nuget' -UserName '331033463@qq.com' -Password 'Tztech@2017'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
