import { TzSuperFormType } from "../TzSuperForm/schema/TzSuperFormSchema";
import { FieldTypeEnum } from "../../common/Enums";

const options = [
    { text: '选项1', value: 1 },
    { text: '选项2', value: 2 },
    { text: '选项3', value: 3 }
]

export interface TzSuperFormField {
    key: string;
    name: string;
    label: string;
    type: TzSuperFormType;
    title: string;
    format?: string | undefined | null;
    options?: any;
    cols?: number; //当前元素占用列个数，默认1
    attrs?: any;
    slots?: any;
}

export const components = [
    {
        title: '内置组件',
        comps: [
            {
                key: '',
                name: '',
                label: '静态文本',
                type: TzSuperFormType.Text,
                title: '静态文本',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '单行输入框',
                type: TzSuperFormType.Input,
                title: '单行输入框',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '密码框',
                type: TzSuperFormType.Password,
                title: '密码框',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '多行输入框',
                type: TzSuperFormType.Textarea,
                title: '多行输入框',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '建议输入框',
                type: TzSuperFormType.Autocomplete,
                title: '建议输入框',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '数字',
                type: TzSuperFormType.Number,
                title: '数字',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '选择器',
                type: TzSuperFormType.Select,
                title: '选择器',
                format: null,
                options: options,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '单选',
                type: TzSuperFormType.Radio,
                title: '单选',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '多选',
                type: TzSuperFormType.Checkbox,
                title: '多选',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '标签',
                type: TzSuperFormType.Tag,
                title: '标签',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '开关',
                type: TzSuperFormType.Switch,
                title: '开关',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '年份',
                type: TzSuperFormType.Year,
                title: '年份',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '月份',
                type: TzSuperFormType.Month,
                title: '月份',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '日期',
                type: TzSuperFormType.Date,
                title: '日期',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '时间和日期',
                type: TzSuperFormType.DateTime,
                title: '时间和日期',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '时间',
                type: TzSuperFormType.Time,
                title: '时间',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '日期范围',
                type: TzSuperFormType.DateRange,
                title: '日期范围',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '多个日期',
                type: TzSuperFormType.Dates,
                title: '多个日期',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '时间和日期范围',
                type: TzSuperFormType.DateTimeRange,
                title: '时间和日期范围',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '时间范围',
                type: TzSuperFormType.TimeRange,
                title: '时间范围',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '周',
                type: TzSuperFormType.Week,
                title: '周',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            // {
            //     key: '',
            //     name: '',
            //     label: '月份范围',
            //     type: TzSuperFormType.MonthRange,
            //     title: '月份范围',
            //     format: null,
            //     options: null,
            //     cols: 1,
            //     attrs: null,
            //     slots: null,
            //     isfinished: false,
            // },
            {
                key: '',
                name: '',
                label: '评分',
                type: TzSuperFormType.Rate,
                title: '评分',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '滑块',
                type: TzSuperFormType.Slider,
                title: '滑块',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '按钮',
                type: TzSuperFormType.Button,
                title: '按钮',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '动态列表',
                type: 'grid',
                title: '动态列表',
                format: null,
                options: {
                    remote: "",
                    schema: [
                        {
                            field: "RowNumber",
                            title: "序号",
                            width: "8%",
                            filterable: false,
                            sortable: false,
                            editable: false,
                            menu: false,
                            type: FieldTypeEnum.Number,
                            index: 0
                        },
                    ]
                },
                cols: 3,
                attrs: null,
                slots: null,
                isfinished: true,
            },
            {
                key: '',
                name: '',
                label: '级联选择',
                type: TzSuperFormType.Cascader,
                title: '级联选择',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: false,
            },
            {
                key: '',
                name: '',
                label: '月份范围',
                type: TzSuperFormType.MonthRange,
                title: '月份范围',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: false,
            },
            {
                key: '',
                name: '',
                label: '上传',
                type: 'upload',
                title: '上传',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: false,
            },
        ]
    },
    {
        title: '扩展组件',
        comps: [
            {
                key: '',
                name: '',
                label: '弹框',
                type: TzSuperFormType.Dialog,
                title: '弹框',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: false,
            },
            {
                key: '',
                name: '',
                label: '超级外壳',
                type: 'shell',
                title: '超级外壳',
                format: null,
                options: null,
                cols: 1,
                attrs: null,
                slots: null,
                isfinished: false,
                tip: '可以组装任何组件'
            },
        ]
    },    
    {
        title: '业务组件',
        comps: [
        ]
    },
]
