name: ASP.NET Core CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: add guget source telerik
      run: |
        nuget sources add -name "telerik.com" -source "https://nuget.telerik.com/nuget" -UserName "331033463@qq.com" -Password "Tztech@2017"
    
    - name: npm install
      run: |
        cd TZ.vNext.Web
        npm install
        
    - name: replacer router.d.ts/vue.d.ts
      run: |
        ".\CIScript\Replacer.exe" ".\TZ.vNext.Web\node_modules\vue-router\types\router.d.ts" "import Vue = require(\"vue\")" "import Vue from 'vue'"        
        ".\CIScript\Replacer.exe" ".\TZ.vNext.Web\node_modules\vue-router\types\vue.d.ts" "import Vue = require(\"vue\")" "import Vue from 'vue'"        
        type ".\TZ.vNext.Web\node_modules\vue-router\types\router.d.ts"
        type ".\TZ.vNext.Web\node_modules\vue-router\types\vue.d.ts"
        
#     - name: Sonarscanner for dotnet
#       uses: Secbyte/dotnet-sonarscanner@v1.1
#       with:
#         buildCommand: dotnet build .
#         testCommand: dotnet test .
#         projectKey: 'Gavin_TZ.vNext'
#         projectName: 'TZ.vNext'
#         sonarOrganisation: 'gavinhome'
#         verbose: "true"
#         openCoverPaths: "tests/coverage.opencover.xml"
#         coverageExclusions: "**test*.cs"
#       env:
#         SONAR_TOKEN: 'a3161a5d555a8fa8021a52e406b00883757b98ce'
#         GITHUB_TOKEN: 'travis encrypt 3f78d7bb5b411c13005794cb16c6bdcdedc446cc'
        
    - name: publish with dotnet
      run: |
        cd TZ.vNext.Web
        dotnet publish --configuration Release
        
    - name: Send dingding notify for build success
      uses: GavinHome/action-dingding@v2      
      if: success()
      with:
        token: 'f8e6693c61f3a970efe789133f5dd4b691ab9a6f0f9058022bf450057a523713'
        body: |
          {
            "msgtype": "link",
            "link": {
                "text": "TZ.vNext 编译成功",
                "title": "Build Sucess",
                "picUrl": "",
                "messageUrl": "https://github.com/GavinHome/TZ.vNext"
            }
          }
          
    - name: Send dingding notify for build failure
      uses: GavinHome/action-dingding@v2
      if: failure()
      with:
        token: 'f8e6693c61f3a970efe789133f5dd4b691ab9a6f0f9058022bf450057a523713'
        body: |
          {
            "msgtype": "link",
            "link": {
                "text": "TZ.vNext 编译失败",
                "title": "Build Failure",
                "picUrl": "",
                "messageUrl": "https://github.com/GavinHome/TZ.vNext"
            }
          }
