name: ASP.NET Core CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: publish with dotnet
      run: |
        sudo apt-get install mono-complete
        mono nuget.exe install
        NuGet Sources Add -Name "telerik.com" -Source "https://nuget.telerik.com/nuget" -UserName "331033463@qq.com" -Password "Tztech@2017"
        cd TZ.vNext.Web
        npm install
        dotnet publish --configuration Release
