name: dingding

# on: 
#   push:
#     branches:
#     - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Send dingding notify
      uses: GavinHome/action-dingding@v1.0     
      with:
        token: ${{ secrets.DING_TOKEN }}
#         body: |
#           {
#             "msgtype": "link",
#             "link": {
#                 "text": "test2",
#                 "title": "test2",
#                 "picUrl": "",
#                 "messageUrl": "https://www.dingtalk.com/s?__biz=MzA4NjMwMTA2Ng==&mid=2650316842&idx=1&sn=60da3ea2b29f1dcc43a7c8e4a7c97a16&scene=2&srcid=09189AnRJEdIiWVaKltFzNTw&from=timeline&isappinstalled=0&key=&ascene=2&uin=&devicetype=android-23&version=26031933&nettype=WIFI"
#             }
#           }
        body: |
          {
            "msgtype": "markdown",
            "markdown": {
                "title": "钉钉消息测试",
                "text": "#### \n 执行结果：${{ job.status }}\n\n > ![screenshot](https://gw.alicdn.com/tfs/TB1ut3xxbsrBKNjSZFpXXcXhFXa-846-786.png)\n > ###### 请点击详情查看 [详情](https://github.com/GavinHome/TZ.vNext/actions) \n"
            }
          }
        

