name: dingding

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Send dingding notify
      uses: GavinHome/action-dingding@v1.0.1      
      with:
        token: f8e6693c61f3a970efe789133f5dd4b691ab9a6f0f9058022bf450057a523713
        body: |
          {
            "msgtype": "link",
            "link": {
                "text": "test2",
                "title": "test2",
                "picUrl": "",
                "messageUrl": "https://www.dingtalk.com/s?__biz=MzA4NjMwMTA2Ng==&mid=2650316842&idx=1&sn=60da3ea2b29f1dcc43a7c8e4a7c97a16&scene=2&srcid=09189AnRJEdIiWVaKltFzNTw&from=timeline&isappinstalled=0&key=&ascene=2&uin=&devicetype=android-23&version=26031933&nettype=WIFI"
            }
          }
        

