name: release

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: add guget source telerik
      run: |
        xcopy packages\* C:\Users\runneradmin\.nuget\packages\ /e
    
    - name: npm install
      run: |
        cd TZ.vNext.Web
        npm install
        
    - name: replacer router.d.ts/vue.d.ts
      run: |
        ".\CIScript\Replacer.exe" ".\TZ.vNext.Web\node_modules\vue-router\types\router.d.ts" "import Vue = require(\"vue\")" "import Vue from 'vue'"        
        ".\CIScript\Replacer.exe" ".\TZ.vNext.Web\node_modules\vue-router\types\vue.d.ts" "import Vue = require(\"vue\")" "import Vue from 'vue'"  

    - name: replacer version
      run: |
        ".\CIScript\Replacer.exe" ".\TZ.vNext.Web\ClientApp\components\home\index.vue.html" "{BUILDNUMBER}" "0.1.0"
        ".\CIScript\Replacer.exe" ".\TZ.vNext.Web\ClientApp\components\home\index.vue.html" "{REVISION}" "${{ github.sha }}"
        ".\CIScript\Replacer.exe" ".\TZ.vNext.Web\ClientApp\components\home\updatelog.vue.html" "{BUILDNUMBER}" "0.1.0"

    # - name: replacer version
    #   run: |
    #     ".\CIScript\Replacer.exe" ".\TZ.vNext.Web\ClientApp\components\home\index.vue.html" "{BUILDNUMBER}" "0.1.0"
    #     type ".\TZ.vNext.Web\ClientApp\components\home\index.vue.html"

    - name: publish with dotnet
      run: |
        cd TZ.vNext.Web
        mkdir publish
        dotnet publish --configuration Release -o publish
        echo ${{ github.repository }} - ${{ github.ref }} - ${{ github.sha }} - 0.1.0 > publish/version.txt
        "../tools/7-Zip/7z.exe" a "publish.zip" "publish/*"
    
    # - uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "TZ.vNext.Web/publish.zip, publish/version.txt"
    #     body: "publishing v0.1.0"
    #     commit: "release"
    #     tag: "v0.1.0"
    #     token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Send dingding notify for build
      if: success()
      uses: GavinHome/action-dingding@v2
      with:
        token: 'f8e6693c61f3a970efe789133f5dd4b691ab9a6f0f9058022bf450057a523713'
        body: |
          {
            "msgtype": "markdown",
            "markdown": {
                "title": "Release v0.1.0",
                "text": "#### TZ.vNext Release \n #### 发布版本：0.1.0 \n\n > ![screenshot](https://gw.alicdn.com/tfs/TB1ut3xxbsrBKNjSZFpXXcXhFXa-846-786.png)\n > ###### 请点击详情查看 [详情](https://github.com/GavinHome/TZ.vNext/releases) \n"
            }
          }
